### ISSUE TITLE
Mianite autosmelting tools bug

### ISSUE THREAD

**Issue by RogueAngelSeven** [EnderMediaDev/Realm-Of-Mianite#1]
When anyone uses a tool with the autosmelting enchantment to mine coal, it crashes the server.
The Error thrown is ConcurrentModificationException which is thrown every time a Collection adds or removes any element while iterating it. That leads me to beleve that there is a bug within one of the mods, rather then a bug brought on by the server configuration and modpack combination.

http://pastebin.com/LxEP3dXb

This Bug Caused 87 of 250 crashes that I have crash logs for.

**Comment by xJon** [comment]
A bug in ttCore, [reported](https://github.com/tterrag1098/ttCore/issues/36) already.
Should get fixed in the future.
Closing this one :)
